language: csharp
mono:
  - latest
dotnet: none
dist: trusty
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libunwind8 liblttng-ust0 libcurl3 libssl1.0.0 libuuid1 zlib1g libicu52
before_script:
  - chmod +x build.sh
script:
  - ./build.sh
env:
  global:
  - PACKAGE_VERSION="0.1.0-alpha"
  - secure: KknLDqIc1wM6ASpdMNQrf9pqTYdND30wwG/E1yAx+UBR9kZiK7b2VvQe25asqlpGzFtqvTTqdYvAk1quOJguyJsU18BIeMYce5KXfRK4zDEmfjzz5FsD6uC/SBs9TPL0ihISAS7TM5xGB6LTRTAa0hCximGNACBdKIKdIQyWmIsDG5qxwor7h61o9zqkM/PMBT9kBgJi47c/EDPr8SA+G28jCtLAbNnwBHcB9DrZNZbAyphQ99pvpvLPz5pt2w7dBz+hJIAM1iS3ctJs6Ya3hTwOqHo6Ui9au466ZmlwV70EUfRJRQcGiZHdf/2aMyZKa/D+BvtdiJq03bhAePrZWahe56IqoLFFTTnDfywz6f5jNvWl6ZmebBHSScEbHdm5JAOP7OQaCuktc16zcJjcscgTWB/jVAqAzaZS3oEZEyYCOil71Ar+pJlmX1yv3rq65nuTnUlze6q7fW2Hmx/M2eUuMP8PVO0d5pI61G7DCZ3oec8dS9h1Jr+7V+2qO49HGSc1GRDgCDIuyI8KV70KzUMo/Lno5XxaBqqNxpfvP7ELj0V7iiZEQdNRYYv30K5/Mf1Jq9bcEfJ+FjNIGAGxBW4PVR6ufFM3ly56IBoLvl084JnZOtj+zAPs6R7xzUArSUOgxeOJS45p/9F06oXJFUxuMIPyzSU/XffKaUpJNTk=
